// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/agents" | "/agents/[id]" | "/agents/new" | "/ai-management" | "/ai-management/agents" | "/ai-management/agents/[id]" | "/ai-management/agents/[id]/edit" | "/ai-management/agents/[id]/knowledge" | "/ai-management/agents/[id]/preview" | "/ai-management/agents/[id]/tools" | "/ai-management/agents/new" | "/ai-management/categories" | "/ai-management/categories/[id]" | "/ai-management/categories/[id]/edit" | "/ai-management/categories/[id]/knowledge" | "/ai-management/categories/new" | "/ai-management/conversations" | "/ai-management/conversations/[id]" | "/ai-management/dashboard" | "/ai-management/knowledge-bases" | "/ai-management/knowledge-bases/[id]" | "/ai-management/knowledge-bases/[id]/edit" | "/ai-management/knowledge-bases/new" | "/ai-management/parent-agent" | "/ai-management/playground" | "/ai-management/settings" | "/ai-management/tools" | "/ai-management/tools/[id]" | "/conversations" | "/login" | "/settings" | "/users"
type AppRouteHandlerRoutes = "/api/agents" | "/api/agents/[id]" | "/api/agents/[id]/documents" | "/api/agents/[id]/documents/[documentId]" | "/api/ai-management/agents/[id]/voices" | "/api/ai-management/categories" | "/api/ai-management/categories/[id]" | "/api/ai-management/conversations" | "/api/ai-management/conversations/[id]" | "/api/ai-management/knowledge-bases" | "/api/ai-management/knowledge-bases/[id]" | "/api/ai-management/knowledge-bases/[id]/documents" | "/api/ai-management/knowledge-bases/[id]/documents/[documentId]" | "/api/ai-management/knowledge-bases/[id]/documents/[documentId]/reindex" | "/api/ai-management/parent-agent" | "/api/ai-management/settings" | "/api/ai-management/settings/elevenlabs" | "/api/ai-management/settings/elevenlabs/validate" | "/api/ai-management/tools" | "/api/ai-management/tools/[id]" | "/api/chat"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/agents": {}
  "/agents/[id]": { "id": string; }
  "/agents/new": {}
  "/ai-management": {}
  "/ai-management/agents": {}
  "/ai-management/agents/[id]": { "id": string; }
  "/ai-management/agents/[id]/edit": { "id": string; }
  "/ai-management/agents/[id]/knowledge": { "id": string; }
  "/ai-management/agents/[id]/preview": { "id": string; }
  "/ai-management/agents/[id]/tools": { "id": string; }
  "/ai-management/agents/new": {}
  "/ai-management/categories": {}
  "/ai-management/categories/[id]": { "id": string; }
  "/ai-management/categories/[id]/edit": { "id": string; }
  "/ai-management/categories/[id]/knowledge": { "id": string; }
  "/ai-management/categories/new": {}
  "/ai-management/conversations": {}
  "/ai-management/conversations/[id]": { "id": string; }
  "/ai-management/dashboard": {}
  "/ai-management/knowledge-bases": {}
  "/ai-management/knowledge-bases/[id]": { "id": string; }
  "/ai-management/knowledge-bases/[id]/edit": { "id": string; }
  "/ai-management/knowledge-bases/new": {}
  "/ai-management/parent-agent": {}
  "/ai-management/playground": {}
  "/ai-management/settings": {}
  "/ai-management/tools": {}
  "/ai-management/tools/[id]": { "id": string; }
  "/api/agents": {}
  "/api/agents/[id]": { "id": string; }
  "/api/agents/[id]/documents": { "id": string; }
  "/api/agents/[id]/documents/[documentId]": { "id": string; "documentId": string; }
  "/api/ai-management/agents/[id]/voices": { "id": string; }
  "/api/ai-management/categories": {}
  "/api/ai-management/categories/[id]": { "id": string; }
  "/api/ai-management/conversations": {}
  "/api/ai-management/conversations/[id]": { "id": string; }
  "/api/ai-management/knowledge-bases": {}
  "/api/ai-management/knowledge-bases/[id]": { "id": string; }
  "/api/ai-management/knowledge-bases/[id]/documents": { "id": string; }
  "/api/ai-management/knowledge-bases/[id]/documents/[documentId]": { "id": string; "documentId": string; }
  "/api/ai-management/knowledge-bases/[id]/documents/[documentId]/reindex": { "id": string; "documentId": string; }
  "/api/ai-management/parent-agent": {}
  "/api/ai-management/settings": {}
  "/api/ai-management/settings/elevenlabs": {}
  "/api/ai-management/settings/elevenlabs/validate": {}
  "/api/ai-management/tools": {}
  "/api/ai-management/tools/[id]": { "id": string; }
  "/api/chat": {}
  "/conversations": {}
  "/login": {}
  "/settings": {}
  "/users": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
