// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../../../src/app/(dashboard)/agents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/agents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/agents/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents/new">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/agents/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/agents">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/agents/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/agents/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/agents/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/agents/[id]/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/agents/[id]/knowledge">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/agents/[id]/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/agents/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/agents/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/agents/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/agents/[id]/preview/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/agents/[id]/preview">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/agents/[id]/preview/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/agents/[id]/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/agents/[id]/tools">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/agents/[id]/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/agents/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/agents/new">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/agents/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/agents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/agents">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/agents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/categories/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/categories/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/categories/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/categories/[id]/knowledge/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/categories/[id]/knowledge">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/categories/[id]/knowledge/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/categories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/categories/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/categories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/categories/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/categories/new">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/categories/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/categories">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/conversations/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/conversations/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/conversations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/conversations">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/conversations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/dashboard">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/knowledge-bases/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/knowledge-bases/[id]/edit">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/knowledge-bases/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/knowledge-bases/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/knowledge-bases/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/knowledge-bases/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/knowledge-bases/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/knowledge-bases/new">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/knowledge-bases/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/knowledge-bases/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/knowledge-bases">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/knowledge-bases/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/parent-agent/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/parent-agent">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/parent-agent/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/playground/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/playground">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/playground/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/settings">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/tools/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/tools/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/tools/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/ai-management/tools/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/ai-management/tools">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/ai-management/tools/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/conversations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/conversations">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/conversations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/(dashboard)/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/users">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/agents/[id]/documents/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/[id]/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/agents/[id]/documents/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/agents/[id]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/[id]/documents">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/agents/[id]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/agents/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/agents/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/agents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/agents">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/agents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/agents/[id]/voices/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/agents/[id]/voices">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/agents/[id]/voices/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/categories/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/categories/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/categories/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/categories/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/categories">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/categories/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/conversations/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/conversations/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/conversations/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/conversations/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/conversations">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/conversations/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/knowledge-bases/[id]/documents/[documentId]/reindex/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/knowledge-bases/[id]/documents/[documentId]/reindex">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/knowledge-bases/[id]/documents/[documentId]/reindex/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/knowledge-bases/[id]/documents/[documentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/knowledge-bases/[id]/documents/[documentId]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/knowledge-bases/[id]/documents/[documentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/knowledge-bases/[id]/documents/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/knowledge-bases/[id]/documents">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/knowledge-bases/[id]/documents/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/knowledge-bases/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/knowledge-bases/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/knowledge-bases/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/knowledge-bases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/knowledge-bases">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/knowledge-bases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/parent-agent/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/parent-agent">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/parent-agent/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/settings/elevenlabs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/settings/elevenlabs">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/settings/elevenlabs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/settings/elevenlabs/validate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/settings/elevenlabs/validate">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/settings/elevenlabs/validate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/settings">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/tools/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/tools/[id]">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/tools/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/ai-management/tools/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/ai-management/tools">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/ai-management/tools/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/api/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/chat">> = Specific
  const handler = {} as typeof import("../../../../src/app/api/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../../../src/app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
